# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJEy1X5cxV7LGk2wpVMRSVYoMK4WtLrh

hey not like that, i got a referal in mitsubishi so i need a project related to that
"""





"""# Task
Develop a machine learning project for Mitsubishi focusing on predictive maintenance using the `ai4i2020.csv` dataset, covering data loading, EDA, preprocessing, model training, evaluation, and recommendations.

## Project Definition & Data Loading

### Subtask:
Formulate a specific problem statement for Mitsubishi (e.g., predictive maintenance for manufacturing machines) and load the `ai4i2020.csv` dataset.

## Project Definition & Data Loading

### Subtask:
Formulate a specific problem statement for Mitsubishi (e.g., predictive maintenance for manufacturing machines) and load the `ai4i2020.csv` dataset.

#### Instructions
1. Based on the project goal of predictive maintenance for manufacturing machines at Mitsubishi, formulate a precise problem statement. For instance, consider defining whether the objective is to predict specific types of machine failures, predict the remaining useful life of a component, or identify anomalous operating conditions indicative of an impending failure.
2. Load the `ai4i2020.csv` dataset into a pandas DataFrame. You can use the `filename` variable which already holds the correct file name.

### Problem Statement

The primary objective of this project is to develop a predictive maintenance model for Mitsubishi's manufacturing machines. Specifically, we aim to **predict impending machine failures and classify the type of failure (e.g., Tool Wear Failure, Heat Dissipation Failure, Power Failure, Overstrain Failure, or Random Failures) based on real-time operational data.** This will enable proactive maintenance interventions, minimize unplanned downtime, reduce repair costs, and optimize the overall efficiency and reliability of Mitsubishi's manufacturing operations.

**Reasoning**:
Now that the problem statement is defined, I will load the `ai4i2020.csv` dataset into a pandas DataFrame as instructed, using the `filename` variable which contains the path to the file.
"""

import pandas as pd

df = pd.read_csv(filename)
print("Dataset loaded successfully. Displaying the first 5 rows:")
df.head()

"""## Exploratory Data Analysis (EDA)

### Subtask:
Understand the dataset's structure, identify key features, check for missing values, and visualize data distributions relevant to machine failures or quality.

**Reasoning**:
The subtask requests to understand the dataset's structure, identify key features, check for missing values, and visualize data distributions. I will start by displaying the concise summary of the DataFrame using `.info()` to get an overview of data types and non-null values.
"""

print("Displaying DataFrame Information:")
df.info()

"""**Reasoning**:
Following the instructions, the next step is to generate descriptive statistics for numerical columns, check for missing values, and identify unique values and their counts for the 'Type' column. I will perform these data inspection tasks in a single code block.


"""

print("\nDescriptive statistics for numerical columns:")
print(df.describe())

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nUnique values and counts for 'Type' column:")
print(df['Type'].value_counts())

"""**Reasoning**:
Now I will proceed with the visualization steps outlined in the instructions. First, I will visualize the distribution of the 'Machine failure' column using a count plot to understand the balance of failure vs. non-failure instances. I will use `seaborn` for plotting.


"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 4))
sns.countplot(x='Machine failure', data=df)
plt.title('Distribution of Machine Failure')
plt.xlabel('Machine Failure (0: No Failure, 1: Failure)')
plt.ylabel('Count')
plt.show()

"""**Reasoning**:
Following the instructions, I will now visualize the distributions of the individual failure type columns ('TWF', 'HDF', 'PWF', 'OSF', 'RNF') using count plots to understand their frequencies.


"""

failure_types = ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']

plt.figure(figsize=(15, 8))
for i, col in enumerate(failure_types):
    plt.subplot(2, 3, i + 1)
    sns.countplot(x=col, data=df)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
plt.tight_layout()
plt.show()

"""**Reasoning**:
Now I will plot histograms for the key numerical features as specified in the instructions to observe their distributions.


"""

numerical_features = ['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']

plt.figure(figsize=(18, 10))
for i, col in enumerate(numerical_features):
    plt.subplot(2, 3, i + 1)
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""## Data Preprocessing & Feature Engineering

### Subtask:
Clean the data, handle outliers, encode categorical variables, and engineer new features that could improve model performance for the defined problem.

## Data Preprocessing & Feature Engineering

### Subtask:
Clean the data, handle outliers, encode categorical variables, and engineer new features that could improve model performance for the defined problem.

#### Instructions
1. Drop the 'UDI' and 'Product ID' columns from the DataFrame `df` as they are identifiers and not relevant for model training.
2. One-hot encode the 'Type' column. Remember to use `drop_first=True` to avoid multicollinearity if appropriate, or keep all categories if a baseline is desired.
3. Create a new multi-class target variable, `Failure_Type`, by combining the individual failure columns ('TWF', 'HDF', 'PWF', 'OSF', 'RNF'). Assign 'No Failure' if 'Machine failure' is 0, and the specific failure type name if one of the individual failure columns is 1. Before creating the column, verify that for any given row, at most one of the specific failure type columns ('TWF', 'HDF', 'PWF', 'OSF', 'RNF') is 1 when 'Machine failure' is 1.
4. Drop the original 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', and 'RNF' columns from the DataFrame after creating the new `Failure_Type` target variable, as they are now consolidated.
5. Identify the numerical features in the DataFrame (e.g., 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]').
6. Standardize these numerical features using `StandardScaler` from `sklearn.preprocessing`. This will scale them to have a mean of 0 and a standard deviation of 1, which is beneficial for many machine learning algorithms.

### Dropping Irrelevant Columns

**Reasoning**:
As per the instructions, 'UDI' and 'Product ID' are unique identifiers that do not carry predictive information for machine failure. Dropping them will help simplify the dataset and prevent potential noise or overfitting in the model.

**Reasoning**:
Now I will execute the first instruction by dropping the 'UDI' and 'Product ID' columns from the DataFrame `df`.
"""

df = df.drop(['UDI', 'Product ID'], axis=1)
print("Columns 'UDI' and 'Product ID' dropped. Displaying the first 5 rows of the updated DataFrame:")
df.head()

"""**Reasoning**:
Now, as per the instructions, I will one-hot encode the 'Type' column. This will convert the categorical 'Type' feature into a numerical format that machine learning models can process. I will use `drop_first=True` to prevent multicollinearity.


"""

df = pd.get_dummies(df, columns=['Type'], drop_first=True, dtype=int)
print("One-hot encoding for 'Type' column applied. Displaying the first 5 rows of the updated DataFrame:")
df.head()

"""**Reasoning**:
Before creating the new `Failure_Type` column, I need to verify that for any given row, at most one of the specific failure type columns ('TWF', 'HDF', 'PWF', 'OSF', 'RNF') is 1 when 'Machine failure' is 1, as per instruction 3. This check ensures data consistency before feature engineering the target variable.


"""

failure_type_columns = ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']

# Filter rows where 'Machine failure' is 1
failure_df = df[df['Machine failure'] == 1]

# Check if more than one specific failure type is 1 in any row
# Summing the failure type columns will give 1 if only one is active, >1 if multiple are active
multi_failure_rows = failure_df[failure_df[failure_type_columns].sum(axis=1) > 1]

if multi_failure_rows.empty:
    print("Verification successful: For rows with 'Machine failure' == 1, at most one specific failure type column is 1.")
else:
    print("Verification failed: There are rows with 'Machine failure' == 1 where multiple specific failure types are 1.")
    print("Displaying the first 5 such rows:")
    print(multi_failure_rows.head())

"""**Reasoning**:
The previous verification revealed that some rows with 'Machine failure' == 1 actually have multiple specific failure types ('TWF', 'HDF', 'PWF', 'OSF', 'RNF') simultaneously marked as 1. This means the individual failure types are not mutually exclusive when a machine failure occurs.

To address this while creating a single multi-class target variable `Failure_Type` as instructed, I will proceed with the following logic:
- If `Machine failure` is 0, `Failure_Type` will be 'No Failure'.
- If `Machine failure` is 1:
    - If exactly one specific failure type (e.g., 'TWF') is 1, `Failure_Type` will be that specific failure name (e.g., 'Tool Wear Failure').
    - If more than one specific failure type is 1, `Failure_Type` will be 'Multiple Failures'.

This approach ensures that each row has a single class label, making it suitable for a multi-class classification problem, and explicitly accounts for the observed data characteristic.

**Reasoning**:
Now, based on the revised logic, I will create the new multi-class target variable `Failure_Type`. This involves setting 'No Failure' for non-failure instances, assigning specific failure types where only one occurs, and marking 'Multiple Failures' for instances with more than one active failure type. After creating this new target, I will drop the original individual failure columns and 'Machine failure' as they are now consolidated.
"""

failure_type_columns = ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']

# Initialize 'Failure_Type' with 'No Failure'
df['Failure_Type'] = 'No Failure'

# Map specific failure types
failure_names = {
    'TWF': 'Tool Wear Failure',
    'HDF': 'Heat Dissipation Failure',
    'PWF': 'Power Failure',
    'OSF': 'Overstrain Failure',
    'RNF': 'Random Failure'
}

# Apply failure types based on the 'Machine failure' and individual failure columns
for index, row in df.iterrows():
    if row['Machine failure'] == 1:
        active_failures = [col for col in failure_type_columns if row[col] == 1]
        if len(active_failures) == 1:
            df.loc[index, 'Failure_Type'] = failure_names[active_failures[0]]
        elif len(active_failures) > 1:
            df.loc[index, 'Failure_Type'] = 'Multiple Failures'

# Drop the original failure columns
df = df.drop(['Machine failure'] + failure_type_columns, axis=1)

print("New 'Failure_Type' target variable created and original failure columns dropped. Displaying value counts and first 5 rows:")
print(df['Failure_Type'].value_counts())
df.head()

"""**Reasoning**:
Now I will identify the numerical features in the DataFrame and then proceed to standardize them using `StandardScaler` as per the instructions. This is crucial for many machine learning algorithms that are sensitive to the scale of input features.


"""

from sklearn.preprocessing import StandardScaler

numerical_features = ['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical features
df[numerical_features] = scaler.fit_transform(df[numerical_features])

print("Numerical features standardized. Displaying the first 5 rows of the updated DataFrame:")
df.head()

"""## Model Selection & Training

### Subtask:
Choose appropriate machine learning models (e.g., classification models for predicting failures or regression for quality deviation) and train them on the preprocessed data.

**Reasoning**:
The first instruction is to separate the features (X) from the target variable ('Failure_Type', y) in the preprocessed DataFrame `df`. This is a necessary first step before splitting the data and training any models.
"""

X = df.drop('Failure_Type', axis=1)
y = df['Failure_Type']

print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

"""**Reasoning**:
Now that features and target are separated, I will split the data into training and testing sets, using `train_test_split` with a `test_size` of 0.2 and stratifying based on the target variable `y` to maintain class proportions, as per instruction 2.


"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""### Addressing Class Imbalance with SMOTE

**Reasoning**:
The previous steps have prepared the data and split it into training and testing sets. However, the target variable `Failure_Type` (as seen in the `.value_counts()` output earlier) is highly imbalanced, with 'No Failure' instances far outnumbering the various failure types. This severe class imbalance can lead to a model that is biased towards the majority class and performs poorly on the minority classes (actual failure types), which are often the most critical to predict.

To mitigate this, I will use **SMOTE (Synthetic Minority Over-sampling Technique)** on the training data (`X_train`, `y_train`). SMOTE works by creating synthetic samples for the minority classes, helping to balance the class distribution and improve the model's ability to learn and predict these less frequent events. This aligns with instruction 3, which specifies using SMOTE from `imblearn.over_sampling`.

**Reasoning**:
Following the explanation, I will now apply SMOTE to the training data (`X_train`, `y_train`) to balance the class distribution, as per instruction 3. I will then display the value counts of the resampled target variable (`y_resampled`) to show the effect of SMOTE.
"""

from imblearn.over_sampling import SMOTE

print("Original class distribution of y_train:")
print(y_train.value_counts())

sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)

print("\nClass distribution of y_train after SMOTE:")
print(y_resampled.value_counts())

"""**Reasoning**:
Now that the training data has been resampled using SMOTE, I will choose a `RandomForestClassifier` as specified in instruction 4 and train it on the `X_resampled` and `y_resampled` data, as per instruction 5.


"""

from sklearn.ensemble import RandomForestClassifier

# Choose and initialize the model
model = RandomForestClassifier(random_state=42)

# Train the model on the SMOTE-resampled training data
model.fit(X_resampled, y_resampled)

print("RandomForestClassifier model trained successfully on SMOTE-resampled data.")

"""## Model Evaluation & Interpretation

### Subtask:
Evaluate the trained model's performance using relevant metrics (e.g., precision, recall, F1-score) and interpret the results to provide insights applicable to Mitsubishi's manufacturing processes.

**Reasoning**:
The first instruction is to use the trained `RandomForestClassifier` model to make predictions on the `X_test` data. I will store these predictions in `y_pred`.
"""

y_pred = model.predict(X_test)
print("Model predictions generated on the test set.")

"""**Reasoning**:
Now that predictions are made, I will calculate the overall accuracy of the model on the test set by comparing `y_pred` with `y_test` and print the result, as per instruction 2.


"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Overall model accuracy on the test set: {accuracy:.4f}")

"""**Reasoning**:
Now, I will generate a classification report using `sklearn.metrics.classification_report` to get a detailed breakdown of precision, recall, and F1-score for each class, as instructed.


"""

from sklearn.metrics import classification_report

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""**Reasoning**:
Now, I will create a confusion matrix using `sklearn.metrics.confusion_matrix` and visualize it with `seaborn.heatmap` to further understand the model's performance across different failure classes, as per instruction 4.


"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Generate the confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

# Plotting the confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()
print("Confusion matrix displayed.")

"""### Interpretation of Model Performance

**Overall Accuracy:** The model achieves an overall accuracy of **96.85%** on the test set. While this appears high, it's crucial to consider the severe class imbalance, where 'No Failure' constitutes the vast majority of instances.

**Strengths:**
*   **Predicting 'No Failure':** The model excels at identifying instances where no machine failure occurs, with a precision of 0.99, recall of 0.97, and an F1-score of 0.98. This indicates high reliability in classifying normal operating conditions.
*   **Heat Dissipation Failure (HDF), Power Failure (PWF), Overstrain Failure (OSF):** The model shows good performance for these failure types, particularly in terms of recall (HDF: 0.95, PWF: 0.94, OSF: 0.88). This means it's effective at identifying most actual occurrences of these failures. The precision, while lower than 'No Failure', is still reasonable (HDF: 0.71, PWF: 0.60, OSF: 0.64), suggesting that when it predicts one of these failures, it's often correct.

**Weaknesses:**
*   **Tool Wear Failure (TWF):** This is the most challenging failure type for the model to predict. It has a very low precision (0.04) and recall (0.12), resulting in an F1-score of only 0.06. This means the model frequently misclassifies TWF and also misses many actual TWF events.
*   **Multiple Failures:** The model struggles with 'Multiple Failures', showing a low precision, recall, and F1-score (0.40 for all). This indicates difficulty in accurately identifying and distinguishing scenarios where multiple failure types occur simultaneously.
*   **False Positives for Minority Classes:** While recall is good for HDF, PWF, and OSF, the precision is lower. For instance, for Heat Dissipation Failure (HDF), a precision of 0.71 means that about 29% of the times the model predicts HDF, it's actually another class (as seen in the confusion matrix, some 'No Failure' and other failure types are predicted as HDF). Similar patterns exist for other minority classes, leading to unnecessary maintenance checks or interventions.

**Implications for Mitsubishi's Predictive Maintenance:**
1.  **Effective Proactive Maintenance for HDF, PWF, OSF:** The model can be a valuable tool for proactive maintenance related to Heat Dissipation, Power, and Overstrain failures. Its high recall for these types means that Mitsubishi can anticipate and address these failures before they lead to significant downtime.
2.  **Further Investigation Needed for TWF and Multiple Failures:** The poor performance on 'Tool Wear Failure' and 'Multiple Failures' suggests that Mitsubishi should not solely rely on this model for these specific issues. Further data collection, feature engineering (e.g., specific sensor data related to tool wear), or more specialized models might be required to accurately predict these complex scenarios.
3.  **Balancing False Positives and False Negatives:** For critical systems, high recall is often prioritized over precision to avoid costly downtime (false negatives). However, a high rate of false positives (predicting a failure when none exists) can lead to unnecessary inspections and maintenance costs. Mitsubishi needs to weigh the costs associated with each type of error to fine-tune the model's threshold or consider additional decision-making layers.
4.  **Actionable Insights:** The model successfully predicts 'No Failure' a high percentage of the time, providing confidence in machine operation when no failure is indicated. For predicted failures, the classification by type allows for targeted and efficient maintenance actions, rather than general troubleshooting.

### Interpretation of Model Performance

**Overall Accuracy:** The model achieves an overall accuracy of **96.85%** on the test set. While this appears high, it's crucial to consider the severe class imbalance, where 'No Failure' constitutes the vast majority of instances.

**Strengths:**
*   **Predicting 'No Failure':** The model excels at identifying instances where no machine failure occurs, with a precision of 0.99, recall of 0.97, and an F1-score of 0.98. This indicates high reliability in classifying normal operating conditions.
*   **Heat Dissipation Failure (HDF), Power Failure (PWF), Overstrain Failure (OSF):** The model shows good performance for these failure types, particularly in terms of recall (HDF: 0.95, PWF: 0.94, OSF: 0.88). This means it's effective at identifying most actual occurrences of these failures. The precision, while lower than 'No Failure', is still reasonable (HDF: 0.71, PWF: 0.60, OSF: 0.64), suggesting that when it predicts one of these failures, it's often correct.

**Weaknesses:**
*   **Tool Wear Failure (TWF):** This is the most challenging failure type for the model to predict. It has a very low precision (0.04) and recall (0.12), resulting in an F1-score of only 0.06. This means the model frequently misclassifies TWF and also misses many actual TWF events.
*   **Multiple Failures:** The model struggles with 'Multiple Failures', showing a low precision, recall, and F1-score (0.40 for all). This indicates difficulty in accurately identifying and distinguishing scenarios where multiple failure types occur simultaneously.
*   **False Positives for Minority Classes:** While recall is good for HDF, PWF, and OSF, the precision is lower. For instance, for Heat Dissipation Failure (HDF), a precision of 0.71 means that about 29% of the times the model predicts HDF, it's actually another class (as seen in the confusion matrix, some 'No Failure' and other failure types are predicted as HDF). Similar patterns exist for other minority classes, leading to unnecessary maintenance checks or interventions.

**Implications for Mitsubishi's Predictive Maintenance:**
1.  **Effective Proactive Maintenance for HDF, PWF, OSF:** The model can be a valuable tool for proactive maintenance related to Heat Dissipation, Power, and Overstrain failures. Its high recall for these types means that Mitsubishi can anticipate and address these failures before they lead to significant downtime.
2.  **Further Investigation Needed for TWF and Multiple Failures:** The poor performance on 'Tool Wear Failure' and 'Multiple Failures' suggests that Mitsubishi should not solely rely on this model for these specific issues. Further data collection, feature engineering (e.g., specific sensor data related to tool wear), or more specialized models might be required to accurately predict these complex scenarios.
3.  **Balancing False Positives and False Negatives:** For critical systems, high recall is often prioritized over precision to avoid costly downtime (false negatives). However, a high rate of false positives (predicting a failure when none exists) can lead to unnecessary inspections and maintenance costs. Mitsubishi needs to weigh the costs associated with each type of error to fine-tune the model's threshold or consider additional decision-making layers.
4.  **Actionable Insights:** The model successfully predicts 'No Failure' a high percentage of the time, providing confidence in machine operation when no failure is indicated. For predicted failures, the classification by type allows for targeted and efficient maintenance actions, rather than general troubleshooting.

## Recommendations & Next Steps

### Subtask:
Based on the model's insights, provide recommendations for improving efficiency or quality control at Mitsubishi, and suggest potential next steps for deployment or further analysis.

## Summary:

### Data Analysis Key Findings

*   **Dataset Overview and Initial Imbalance**: The `ai4i2020.csv` dataset contains 10,000 entries and 14 columns with no missing values. Initial analysis revealed a significant class imbalance, with only 3.39% of instances representing machine failures and individual failure types being even rarer.
*   **Unique Failure Event Characteristics**: A crucial finding during preprocessing was that when a 'Machine failure' occurred, multiple specific failure types (e.g., 'Tool Wear Failure', 'Heat Dissipation Failure') could be active simultaneously, contrary to an initial assumption of mutual exclusivity. This led to the creation of a 'Multiple Failures' class in the target variable.
*   **Effective Class Imbalance Handling**: To address the severe class imbalance in the training data, SMOTE (Synthetic Minority Over-sampling Technique) was successfully applied. This balanced the distribution of all failure types for model training, ensuring each class had an equal number of samples (7,736 instances).
*   **Overall Model Accuracy**: The trained RandomForestClassifier achieved an overall accuracy of 96.85% on the test set.
*   **Strong Performance for 'No Failure' and Specific Failure Types**: The model demonstrates excellent performance in identifying 'No Failure' instances (precision: 0.99, recall: 0.97, F1-score: 0.98). It also shows good recall for 'Heat Dissipation Failure' (0.95), 'Power Failure' (0.94), and 'Overstrain Failure' (0.88), indicating its effectiveness in detecting most occurrences of these critical failures.
*   **Weak Performance for 'Tool Wear Failure' and 'Multiple Failures'**: The model struggled significantly with predicting 'Tool Wear Failure' (precision: 0.04, recall: 0.12, F1-score: 0.06) and 'Multiple Failures' (precision, recall, F1-score: 0.40 for all), suggesting challenges in accurately identifying or distinguishing these complex scenarios.

### Insights or Next Steps

*   **Prioritize Specific Failure Predictions**: Mitsubishi can confidently leverage the model for proactive maintenance strategies concerning 'Heat Dissipation Failure', 'Power Failure', and 'Overstrain Failure' due to the model's high recall for these types, allowing for targeted interventions.
*   **Enhance Model for Challenging Failure Types**: Further investigation and model refinement are necessary for 'Tool Wear Failure' and 'Multiple Failures'. This could involve collecting more specific sensor data related to tool wear, engineering new features, or exploring more specialized machine learning models to improve their prediction accuracy.
"""